//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bán_Hàng_Onl_WebForm.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Orders = new HashSet<Order>();
        }

        [DisplayName("Mã Khách hàng")]
        public decimal UserID { get; set; }
        [DisplayName("Họ và Tên")]
        [Required(ErrorMessage = "Vui lòng nhập vào họ và tên")]
        public string FullName { get; set; }
        [DisplayName("Tài Khoản")]
        [Required(ErrorMessage = "Vui lòng nhập vào tài khoản")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập vào mật khẩu")]
        [DisplayName("Mật khẩu")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Required(ErrorMessage = "Vui lòng chọn giới tính")]
        [DisplayName("Giới Tính")]
        public Nullable<bool> gender { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập ngày sinh")]
        [DisplayName("Ngày Sinh")]
        public Nullable<System.DateTime> birthday { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập email")]
        [DisplayName("Email")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập số điện thoại")]
        [DisplayName("Số Điện Thoại")]
        public string phone { get; set; }
        public Nullable<int> Role { get; set; }
        public Nullable<bool> status { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public string RegisterFail { get; set; }
        [DisplayName("Xác Nhận Mật Khẩu")]
        [Required(ErrorMessage = "Vui lòng xác nhận mật khẩu")]
        [DataType(DataType.Password)]
        public string ConfrimPassword { get; set; }
        public string LoginError { get; set; }
    }
}
