//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bán_Hàng_Onl_WebForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public decimal VoucherID { get; set; }
        public string VoucherName { get; set; }
        public Nullable<double> VoucherPrice { get; set; }
        public Nullable<decimal> status { get; set; }
    }
}
